# steps:
#   - name: maven:3-jdk-8
#     entrypoint: mvn
#     args: ["install"]
#   - name: maven:3-jdk-8
#     entrypoint: mvn
#     args: ["package", "-Dmaven.test.skip=true","appengine:deploy"]
# #  - name: gcr.io/cloud-builders/docker
# #    args: ["build", "-t", "gcr.io/$PROJECT_ID/inventorymanagement", "--build-arg=JAR_FILE=target/inventorymanagement-1.0.0.0.jar", "."]
# #images: ["gcr.io/$PROJECT_ID/inventorymanagement"]

steps:
  # Build the Spring Boot application
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install']
    
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']